- utilcode/src/main/java/com/blankj/utilcode/utils/FileUtils.java
修复由于获取文件拓展名错误，导致的一系列问题（如6.0安装APK异常）
> fix FileUtils.getFileExtension()

- utilcode/src/main/java/com/blankj/utilcode/utils/AppUtils.java
getRunningTasks 在 API 21 已被遗弃，已经不能正常获取。通过 getRunningAppProcesses ，仅可以获取自己应用的包名，其他应用不能获取，所以只能判断应用是否处于前台，而不能判断前台应用是哪个。系统应用可通过 UsageStatsManager 来获取前台应用包名。
> 判断应用程序是否在前台

- utilcode/src/main/java/com/blankj/utilcode/utils/DeviceUtils.java
isDeviceRoot can be confused for a method that checks for root directory of device.
isDeviceRooted will prevent that confusion
> DeviceUtils: change method name to isDeviceRooted

- utilcode/src/main/java/com/blankj/utilcode/util/TimeUtils.java
给DateUtils添加一些新方法：根据给定的日期和时间间隔计算新日期
> 添加获取指定时间间隔后的日期

- utilcode/src/main/java/com/blankj/utilcode/util/ShellUtils.java
shell结果换行。
之前的结果会将shell返回后的字符串拼接在一起，如果使用ls 、ps等这样的命令导致输出的文件夹都拼接在一起无法友好的查看，也不符合命令输出的格式。
> 添加shell返回换行

- app/build.gradle
- build.gradle
- subutil/build.gradle
- utilcode/build.gradle
This *PR* applies [Traute](http://traute.oss.harmonysoft.tech/) *javac* plugin to the project in order to have runtime *null*-checks for method parameters marked by *NonNull* annotation.  
E.g. consider [BaseDrawerActivity.$1. onNavigationItemSelected()](https://github.com/Blankj/AndroidUtilCode/blob/master/app/src/main/java/com/blankj/androidutilcode/base/BaseDrawerActivity.java#L32). Resulting bytecode looks like if it's compiled from the source below:  
```java
public boolean onNavigationItemSelected(@NonNull MenuItem item) {
if (item == null) {
throw new NullPointerException("String Argument 'item' of type MenuItem (#0 out of 1, zero-based) is marked by @android.support.annotation.NonNull but got null for it");
}
switch (item.getItemId()) {
...
```
Here are the details: …
> Null-checks for @NonNull method arguments

- subutil/src/main/java/com/blankj/subutil/util/ClipboardUtils.java
- subutil/src/main/java/com/blankj/subutil/util/LocationUtils.java
- subutil/src/main/java/com/blankj/subutil/util/Utils.java
Since you replaced `Context` by `Application` in utilcode's `Utils.java`, `getContext` is now undefined inside subutil code. Actually, you didn't update subutilcode's `Utils.java`, so `getContext` might work inside library files, but their classes should be copied by user, which probably implemented utilcode and isn't interested in downloading subutilcode's `Utils.java`, so it wouldn't work. 
Equalizing both `Utils.java` and updating subutil context retrieval, which I did, should do the work :)
> Update subutil context retrieval

- utilcode/src/main/java/com/blankj/utilcode/util/ToastUtils.java
1、修复构造Toast时如果传入的是Activity Context可能造成的内存泄漏，静态Toast改成软引用，只用来取消Toast的连续显示。
2、增加一个设置字体大小的方法，项目中需要用的时候发现没有，只能通过自定义实现。
> Fix memory leak in ToastUtils. Add a method to set the text size.

- utilcode/src/main/java/com/blankj/utilcode/util/EncodeUtils.java
- utilcode/src/test/java/com/blankj/utilcode/util/EncodeUtilsTest.java
> Added binary encoding

- utilcode/lib/src/main/java/com/blankj/utilcode/util/LogUtils.java
> enhanced object to string in LogUtils

- lib/utilcode/src/main/java/com/blankj/utilcode/util/UriUtils.java
从”最近下载“选择文件时，uri ：content://com.android.providers.downloads.documents/msf:xxx。Long.valueOf("msf:xxx")会抛出异常
> 修复从SAF选择文件时id解析异常的问题

- lib/utilcode/src/main/java/com/blankj/utilcode/util/ColorUtils.java
add static  to ColorUtils.isLightColor
> static ColorUtils.isLightColor

- lib/utilcode/src/main/java/com/blankj/utilcode/util/ScreenUtils.java
Added 6 new very useful methods.
1. getScreenXDpi() which returns the Width (X) density in DPI.
2. getScreenYDpi() which returns the Height (Y) density in DPI.
3. calculateDistanceByX() which returns the distance between the given View's X (start point of View's width) and the screen width.
4. calculateDistanceByY() which returns the distance between the given View's Y (start point of View's height) and the screen height.
5. getViewX() which returns the X coordinate of the given View on the screen.
6. getViewY() which returns the Y coordinate of the given View on the screen.
> Added new methods (features)

- lib/utilcode/src/main/java/com/blankj/utilcode/util/RegexUtils.java
/**
* Returns the domain part of a given Email address
*
* @param email The Email address. E.g Returns "protonmail.com" from the given Email "johnsmith@protonmail.com".
* @return the domain part of a given Email address.
*/
public static String extractEmailProvider(String email) {
return email.substring(email.lastIndexOf("@") + 1);
}
/**
* Returns the username part of a given Email address. E.g. Returns "johnsmith" from the given Email "johnsmith@protonmail.com".
*
* @param email The Email address.
* @return the username part of a given Email address.
*/
public static String extractEmailUsername(String email) {
return email.substring(0, email.lastIndexOf("@"));
}
/**
* Return whether a given Email address is on a specified Email provider. E.g. "johnsmith@protonmail.com" and "gmail.com" …
> Added 4 useful methods

- lib/utilcode/src/main/java/com/blankj/utilcode/util/KeyboardUtils.java
//这里会发生内存泄漏 如果不设置为null
contentView.setTag(TAG_ON_GLOBAL_LAYOUT_LISTENER, null);
> 修复了一个内存泄漏的问题

- lib/utilcode/src/main/java/com/blankj/utilcode/util/TimeUtils.java
Useful in situations where you want to verify that the device has a correct time set, to avoid fraud, or if you want to prevent the user from messing with the time and abusing your "one-time" and "expiring" features.
> isUsingNetworkProvidedTime()

- lib/utilcode/src/main/java/com/blankj/utilcode/util/NetworkUtils.java
1. isBehindProxy():
Returns true if device is connecting to the internet via a proxy, works for both Wi-Fi and Mobile Data.
Code:
`public static boolean isBehindProxy(){
return !(System.getProperty("http.proxyHost") == null || System.getProperty("http.proxyPort") == null);
}`
2. isUsingVPN():
Returns true if device is connecting to the internet via a VPN.
`public static boolean isUsingVPN(){
ConnectivityManager cm = (ConnectivityManager) com.blankj.utilcode.util.Utils.getApp().getSystemService(Context.CONNECTIVITY_SERVICE);
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
return cm.getNetworkInfo(ConnectivityManager.TYPE_VPN).isConnectedOrConnecting()
} else {
return cm.getNetworkInfo(NetworkCapabilities.TRANSPORT_VPN).isConnectedOrConnecting()
}
}`
> NEW Methods: NetworkUtils: isBehindProxy(), isUsingVPN() (All APIs supported)

- lib/utilcode/src/main/java/com/blankj/utilcode/util/AppUtils.java
1. isFirstTimeInstall():
If you want to know whether this is the first time installation of this app in this device.
2. isAppUpgraded():
If you want to know whether the current version was installed over a previous version (update/upgrade) or if it is freshly installed (clean install).
Code:
* Return true if this is the first ever time that the application is installed on the device.
*
* @return true if this is the first ever time that the application is installed on the device.
` 
public static boolean isFirstTimeInstall(){
try {
Long firstInstallTime = Utils.getApp().getPackageManager().getPackageInfo(this.getAppPackageName(), 0).firstInstallTime;
Long lastUpdateTime = Utils.getApp().getPackageManager().getPackageInfo(this.getAppPackageName(), 0).lastUpdateTime;
return firstInstallTime …
> NEW Methods: AppUtils: isFirstTimeInstall(), isAppUpgraded() (All APIs supported)

- lib/utilcode/src/main/java/com/blankj/utilcode/util/MessengerUtils.java
原始消息在发送之后会被系统回收, 服务端循环向客户端发送消息时, 会发送被使用过的消息导致异常发生. 
需要创建一个副本进行消息发送
> Fix: MessengerUtils java.lang.IllegalStateException

- lib/utilcode/src/main/java/com/blankj/utilcode/util/JsonUtils.java
Check if a given input is a JSONObject or a JSONArray.
Code: 
1. isJSONObject(input)
```
/**
* Checks if a given input is a JSONObject.
*
* @param input Anything.
* @return true if it is a JSONObject.
*/
public static <T> boolean isJSONObject(final T input) {
return input instanceof JSONObject;
}
```
2. isJSONArray(input)
```
/**
* Checks if a given input is a JSONArray
*
* @param input Anything.
* @return true if it is a JSONArray.
*/
public static <T> boolean isJSONArray(final T input) {
return input instanceof JSONArray;
}
```
> 2 new methods: isJSONObject() and isJSONArray()

- lib/utilcode/src/main/res/xml/util_code_provider_paths.xml
> fix bug 1544

- lib/utilcode/README-CN.md
- lib/utilcode/README.md
- lib/utilcode/src/main/AndroidManifest.xml
> [M] 修改BarUtils方法列表及描述
